### PR TITLE
Fix misspelling in callbacks spec

### PR DESCRIPTION
**Pull request by johncblandii**
Highly important and super awesome update to the spec to correct misspellings.

FYA: @gonzalo-bulnes

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
Hi @johncblandii,

Nice, I'll include it in the next release : )
Thank you!

**Comment by johncblandii** [comment]
My pleasure.

**Comment by gonzalo-bulnes** [comment]
Aaah, I forgot this one! Second time's a charm. 😉

**Comment by gonzalo-bulnes** [comment]
Thank you again @johncblandii !

**Comment by johncblandii** [comment]
No problem, @gonzalo-bulnes.

**Pull request closed without merging**
