### PR TITLE
Allow for custom authentication identifier attribute

### PR DESCRIPTION
**Pull request by nicolo**
This is my solution for allowing a user to configure a custom identifying attribute to be used for authentication which is discussed in issue https://github.com/gonzalo-bulnes/simple_token_authentication/issues/68. I took a few things from @wielinde's https://github.com/gonzalo-bulnes/simple_token_authentication/pull/119 and @proGM's https://github.com/gonzalo-bulnes/simple_token_authentication/pull/90. I decided to implement my on solution due to the recent major changes implemented in the gem. @gonzalo-bulnes I'd love to hear your comments and work to get this merged in.

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
Hey @nicolo, nice PR : ) !

**Comment by nicolo** [comment]
@gonzalo-bulnes anything left to do before getting this merged in? Just let me know, and I'll get on it.  Thanks!

**Comment by computerion** [comment]
Thanks for writing this. It's the only way currently for one of my projects to migrate away from Devise's deprecated Token Authenticable. I'll be using your fork until the branch is merged :)

**Comment by gonzalo-bulnes** [comment]
Hi @computerion, until the `v1.8.0` is released you can try this feature specifying the `master` branch in your `Gemfile`:

```ruby
# Gemfile

# ...

gem 'simple_token_authentication`, git: 'https://github.com/gonzalo-bulnes/simple_token_authentication.git', branch: 'master'

# ...

```

Any feedback would be greatly appreciated!
Regards!

**Pull request closed without merging**
