### PR TITLE
Allow ActionController::Metal subclassed controllers to acts_as_token_authentication_handler_for

### PR DESCRIPTION
**Pull request by singfoom**
Thanks for all your hard work!

In order to write the fastest JSON APIs around, I'd like to be able to use ActionController::Metal as my base API controller.  This PR allows that.  All tests are passing.

An example app using the branch for the PR is available here, I've run it successfully.

https://github.com/singfoom/metal_simple_token_authentication_example

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
Hi @singfoom!

That's an awesome PR! I'm reviewing it and will comment here on the go.

**Comment by singfoom** [comment]
Sorry about that.  I looked through the codebase to make sure I got all of the specs but I missed that one.

**Comment by gonzalo-bulnes** [comment]
Don't worry @singfoom your PR is really awesome!

**Comment by gonzalo-bulnes** [comment]
I just merged it (as #211), I'll now make sure everything is fine using your example app, and I'll realease **v1.12.0**.

**Comment by gonzalo-bulnes** [comment]
_Simple Token Authentication_ **v1.12.0** is out with your adapter, thank you again @singfoom!

**Pull request closed without merging**
