### PR TITLE
Change to MIT License

### PR DESCRIPTION
**Pull request by jbosse**
Since this code originally cam from Devise and the Devise gem is under the MIT-LICENSE.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
Don't forget to change the gemspec as well :)

https://github.com/gonzalo-bulnes/simple_token_authentication/blob/master/simple_token_authentication.gemspec#L14

**Comment by gonzalo-bulnes** [comment]
Hello @jbosse,


**1. About the origin of this project**
 
This gem was written using an explanation and an example written by J. Valim. (I've already detailed the origin of this project, albeit in [a slightly different context][comment], please let me quote the relevant sections of that comment here - with custom **emphasis**.)

>  **José Valim shared both his explanations and his code as a [gist][gist], which provides no obvious way to define license terms. That being said, if he wanted to specify re-use conditions for these code examples, he could have done so in a multitude of ways.**

> On the _Simple Token Authentication_ side:
- the credits aim at crediting J. Valim for sharing his work while not charging him with any undue responsibility
- the copyright and license disclaimers, on the other hand, aim at defining the conditions under which the code can be used

> These are two distinct concerns: the first is mostly ethical and certainly optional, the second is legal and mandatory. **[** _This paragraph was closely tied to the original context, I kept it for consistency._ **]**

> The gem code was written by its [contributors][contributors] (including, but not limited to myself), and any of them can claim copyright on it as part of a PR ([keep existing copyright notices, add you own][howto]). I don't add any copyright notice by myself because I have no reason to make that decision on behalf of any of them.

> **The gem code is also deeply inspired in José Valim's gist**, and would he want to claim copyright on it (the gist), of course that it would extend to the gem. But again, I have no reason to make that decisions for anybody on this topic. And no reason to infer anything from an absence of claim.

In that last paragraph, what's true for the copyright claim, is true for the licence terms.


**2. About Devise being distributed under the MIT license terms**

The _Simple Token Authentication_ gem provides:

- A refactored version of the J. Valim's gist, aimed at make it's usage more convenient. (Most of that can still be seen in [this gist][concern] I wrote back then to share that refactoring.)
- A set of additions aimed at making safe token authentication conveniently applicable to a wide range of scenarios.
 
Beyond the strict limits of this code, what you can or cannot do when combining multiple pieces of code is regulated by their licenses, and whether they are _[compatible][compatibility]_ or not.

The so-called MIT license [is compatible with the GPL][expat]. That does mean that you can, within the terms of the MIT license, merge a piece of code under that license and a piece of code under the GPL to produce a larger piece of code.

The GPL also allows that merge of MIT-licensed code, provided the compound work is distributed under the GPL terms. The MIT license is said to be compatible with the GPL because it [allows the compound work to be distributed under these terms][merge]. (This means that _if some code were licensed under the MIT terms_, another project built from it could, or not, be licensed under the MIT license terms. That depends on the other part of the project and is not automatic. And that's certainly, at least in part, why the MIT license is said to be a _permissive_ license.)

Back to this code. _**If all or parts of the code contained in J. Valim gist were licensed under the MIT terms**_, another project built from it could, or not, be licensed under the MIT license terms.

I decided to share the portions of Simple Token Authentication gem I wrote under the GPL terms, because I want any _Simple Token Authentication_ user to be able to use any improvement available in any public fork of it. 

As a consequence, as we speak (**v1.12.0**), Simple Token Authentication is licenced under the _GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version_. ([source][license])
(Note that the GPL does not regulate how you _use_ the code, nor whether or not you modify it until you _distribute_ your changes. So you can do whatever you want in a private fork for your own usage.)


What _**if the content of the J. Valim gist were not licensed under the MIT license terms**_? That's a good question too, IMO, and a more complex one.
As an answer: because the sharing intention is quite clear, I assume that publishing the code in a gist is a sort of [informal license statement][informal]. Most of what I said stays the same, and for the sections strictly related to the MIT license, I think it doesn't change much - until further notice.

That being said, the not-GPL-licensed part of it (maybe, or not, MIT licensed) is still available, and is referred to in the second link of the `README`:

> In this [this gist][gist], Devise's José Valim explains how token authentication should be performed in order to remain safe. ([source][readme])

I would also say that the [refactoring I wrote][concern] doesn't either mention any license terms, and I think you can assume the same thing I did about the J. Valim's gist - that's to say consider it part of the non-GPL-licensed code.

**What I take out of this**

Licenses are a complex topic -often treated in an offhanded manner- and clarifying this needed to be done at some point. Thank you for raising the concern, and I hope that this long response made things clearer.

I also realised that at this point the last part of the introduction may be a bit misleading:

> This gem packages the content of the gist.

_Simple Token Authentication_ is not only about packaging, but also extending quite a lot.

 To be honest, I hadn't really noticed that until your PR (thank you). I don't think it's such a big issue, yet I may fix that in a future release.

Thank you for caring, and for reading :P 

Regards!



  [comment]: https://github.com/gonzalo-bulnes/simple_token_authentication/pull/78#issuecomment-47137119
  [gist]: https://gist.github.com/josevalim/fb706b1e933ef01e4fb6
  [readme]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.12.0/README.md

  [contributors]: https://github.com/gonzalo-bulnes/simple_token_authentication/graphs/contributors
  [howto]: http://www.gnu.org/licenses/gpl-howto.html
  [concern]: https://gist.github.com/gonzalo-bulnes/7659739

  [compatibility]: https://www.gnu.org/licenses/gpl-faq.html#WhatIsCompatible
  [expat]: https://www.gnu.org/licenses/license-list.html#Expat
  [merge]: https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean
  [license]: https://github.com/gonzalo-bulnes/simple_token_authentication/blob/v1.12.0/README.md#license
  [informal]: https://www.gnu.org/licenses/license-list.html#informal

**Comment by lowjoel** [comment]
It may just be me, and IANAL -- but by compatibility, GNU says (in the same FAQ)

> All GNU GPL versions permit such combinations privately; they also permit distribution of such combinations provided the combination is released under the same GNU GPL version. The other license is compatible with the GPL if it permits this too.

Which means the GPL does taint MIT-licensed projects to be GPL as well.

**Comment by gonzalo-bulnes** [comment]
That's exact @lowjoel, but I would say that's a different issue: would it be beneficial to move to an MIT license?

As I [said][why], I did choose the GPL for _Simple Token Authentication_  because I want any of its users to be able to use any improvement available in any public fork of it. The MIT license provides no such guaranty, and at this point I'm not convinced at all it would be a good change.

  [why]: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/240

**Comment by lowjoel** [comment]
Oh, OK, back to our email conversation then :stuck_out_tongue:

**Comment by jbosse** [comment]
Wow. Thank you for such a thoughtful explanation. 

It was my horrifically incorrect assumption that the GPL license was simply a result of no thought, not the result of such carefully considered thinking.

I respectfully withdraw this PR.

**Comment by gonzalo-bulnes** [comment]
You're welcome @jbosse - all this is definitely not obvious and it was a good opportunity to document it. Thank you for caring about this stuff.

**Pull request closed without merging**
