### PR TITLE
Remove obsolete rails and ruby versions

### PR DESCRIPTION
**Pull request by oskarpearson**
Remove support for obsolete Ruby, Rails, and Devise versions

- Require Ruby 2.7 or later, since all versions prior are unsupported
- Require Rails 6.0 or later, since all versions prior are unsupported
- Require at least Devise 4.7.2 - since that's when Ruby 2.7 support was added.
- Update to use github actions instead of TravisCI for testing (as per https://github.com/gonzalo-bulnes/simple_token_authentication/pull/391#issuecomment-1309932821 )

## Context

The [Rails 7 upgrade](https://github.com/gonzalo-bulnes/simple_token_authentication/pull/391) is currently blocked by lack of functioning CI. @pglombardo helpfully added github actions at https://github.com/gonzalo-bulnes/simple_token_authentication/pull/391#issuecomment-1309932821 but CI wouldn't work.

Rather than trying to fix support for obsolete and unsupported versions of Ruby, Rails, and Devise, this PR drops them. Hopefully this means that Rails 7 and Ruby 3.* can be added once CI cleanly works

### CODE REVIEW

**Review by pglombardo — APPROVED** [review]
Great job.  Hopefully this will help in getting a new gem version out.

**Comment by oskarpearson** [comment]
@gonzalo-bulnes apologies for the direct ping, but I wanted to check what you thought, generally?

I’ve not used the appraisals gem before so wondered if I had done anything incorrectly there too

**Comment by gonzalo-bulnes** [comment]
Hi @oskarpearson no problem :+1: 

**My thoughts**: Where you draw the line of support for older software is always arbitrary. By that I mean: it is never perfect, and there isn't a single answer to where that line should be. Because of that, I take the position of not breaking backwards compatibility unless necessary, and I doesn't seems necessary to me in this case. I'm leaving Ruby 1.9.3 in observation for time sake, but otherwise there is no need to constrain Rails or Devise versions further.

I've added a GitHub Actions workflow (#397) that runs pretty much the same combination of Ruby and Rails versions that Travis CI used to run, and made the [one minor adjustment](https://github.com/gonzalo-bulnes/simple_token_authentication/pull/397/commits/752a4c5be1d176d3f33a428237b516bceea20108) that was causing a legit test failure.

Test matrices like this one, with multiple version of Ruby and separate gemfiles can be overwhelming, I understand that. Especially when you're keen on excluding all unnecessary combinations to save some CPU time (:earth_americas:). But they're what has allowed you to upgrade this gem without breaking changes so far! Suffice to compare how many times the gem was upgraded to how many times the matrix was set up, to convince me that they're well worth the trouble :slightly_smiling_face: YMMV

I'll close this PR when merging #394, but I appreciate your help to get support for Rails 7 across the finish line, it is significant. Thank you!

**Comment by oskarpearson** [comment]
@gonzalo-bulnes thanks for taking the time to review. No problems at all from my side. Ta!

**Pull request closed without merging**
